// This file was auto-generated by ML.NET Model Builder. 

using System;
using SpamdetectorML.Model;

namespace SpamdetectorML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Message = @"Ok",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual IsSpam with predicted IsSpam from sample data...\n\n");
            Console.WriteLine($"Message: {sampleData.Message}");
            Console.WriteLine($"\n\nPredicted IsSpam value {predictionResult.Prediction} \nPredicted IsSpam scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
