// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace SpamdetectorML.Model
{
    public class ModelInput
    {
        [ColumnName("IsSpam"), LoadColumn(0)]
        public string IsSpam { get; set; }


        [ColumnName("Message"), LoadColumn(1)]
        public string Message { get; set; }


    }
}
